import React,{useEffect,useMemo,useState} from 'react';
import Sidebar from '../components/Sidebar';
import api from '../../api/api';
const LABEL={pending:'Ombi jipya',confirmed:'Imethibitishwa',collected:'Imechukuliwa',in_transit:'Safarini',delivered:'Imefikishwa',completed:'Imekamilika',cancelled:'Imeghairiwa'};
export default function AdminShipments({activePage,onNavigate,onLogout}){
 const [rows,setRows]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[q,setQ]=useState(''),[status,setStatus]=useState('all');
 const load=()=>{setLoading(true);setError('');api.get('/shipments/admin?limit=300').then(r=>setRows(r.data||[])).catch(e=>setError(e.response?.data?.message||'Imeshindikana kupakia shipments')).finally(()=>setLoading(false));};
 useEffect(load,[]);
 const shown=useMemo(()=>rows.filter(s=>(status==='all'||s.status===status)&&(!q||[s.trackingNumber,s.senderName,s.senderPhone,s.receiverName,s.receiverPhone,s.itemDescription,s.originCity,s.destinationCity].some(v=>String(v||'').toLowerCase().includes(q.toLowerCase())))),[rows,q,status]);
 return <div style={{display:'flex',minHeight:'100vh',background:'#f8fafc',fontFamily:'Manrope,Inter,sans-serif'}}><Sidebar activePage={activePage} onNavigate={onNavigate} onLogout={onLogout}/><main style={{marginLeft:250,flex:1,padding:32}}>
 <div style={{display:'flex',justifyContent:'space-between',gap:16,alignItems:'center',marginBottom:22}}><div><h1 style={{fontSize:22,margin:0,color:'#0f172a'}}>📦 Shipments</h1><p style={{margin:'5px 0 0',color:'#64748b',fontSize:13}}>Mizigo yote iliyoanzishwa kupitia Kentexa — user, seller, walk-in na order.</p></div><button onClick={load} style={{border:0,borderRadius:9,padding:'10px 16px',background:'#2563eb',color:'#fff',fontWeight:800}}>Onyesha upya</button></div>
 <div style={{display:'grid',gridTemplateColumns:'2fr 1fr',gap:10,marginBottom:16}}><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Tafuta tracking, sender, receiver, simu, route..." style={{padding:12,border:'1px solid #cbd5e1',borderRadius:10,fontSize:14}}/><select value={status} onChange={e=>setStatus(e.target.value)} style={{padding:12,border:'1px solid #cbd5e1',borderRadius:10,fontSize:14}}><option value="all">Status zote</option>{Object.entries(LABEL).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div>
 {error&&<div style={{padding:12,background:'#fee2e2',color:'#b91c1c',borderRadius:10}}>{error}</div>}
 {loading?<div>Inapakia…</div>:<div style={{display:'grid',gap:10}}>{shown.map(s=><div key={s.id} style={{background:'#fff',borderRadius:14,padding:16,boxShadow:'0 2px 8px rgba(0,0,0,.05)'}}>
 <div style={{display:'flex',justifyContent:'space-between',gap:12}}><div><strong style={{fontSize:15}}>{s.itemDescription||'Mzigo'}</strong><div style={{fontSize:12,color:'#64748b',marginTop:4}}>{s.trackingNumber||('Shipment #'+s.id)} · {s.intakeChannel||'—'}</div></div><span style={{fontSize:12,fontWeight:900,color:'#2563eb'}}>{LABEL[s.status]||s.status}</span></div>
 <div style={{fontSize:14,fontWeight:800,color:'#334155',marginTop:10}}>{s.originCity} → {s.destinationCity}</div>
 <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:8,marginTop:10,fontSize:12,color:'#475569'}}><div>Mtumaji: <strong>{s.senderName||s.requesterName||'—'}</strong><br/>{s.senderPhone||s.requesterPhone||'—'}</div><div>Mpokeaji: <strong>{s.receiverName||'—'}</strong><br/>{s.receiverPhone||'—'}</div><div>Uzito: <strong>{Number(s.weightKg||0)} kg</strong><br/>Bei: <strong>{s.priceQuoted?('TZS '+Number(s.priceQuoted).toLocaleString()):'—'}</strong></div><div>Imeundwa: <strong>{s.createdAt?new Date(s.createdAt).toLocaleString('sw-TZ'):'—'}</strong></div></div>
 {s.trackingNumber&&<button onClick={()=>onNavigate('TrackParcel-'+s.trackingNumber)} style={{marginTop:12,border:'1px solid #bfdbfe',background:'#eff6ff',color:'#1d4ed8',padding:'8px 12px',borderRadius:8,fontWeight:800,cursor:'pointer'}}>Fungua tracking</button>}</div>)}{!shown.length&&<div style={{background:'#fff',padding:28,borderRadius:14,textAlign:'center',color:'#64748b'}}>Hakuna shipment inayolingana.</div>}</div>}</main></div>;
}