import { MigrationInterface, QueryRunner } from 'typeorm';

export class AddTransportRecurringSchedule1788291600000 implements MigrationInterface {
  name = 'AddTransportRecurringSchedule1788291600000';

  public async up(q: QueryRunner): Promise<void> {
    await q.query(`
      CREATE TABLE IF NOT EXISTS public.transport_route_schedule (
        id SERIAL PRIMARY KEY,
        "providerId" integer NOT NULL,
        "routeId" integer NOT NULL,
        "scheduleType" varchar(20) NOT NULL DEFAULT 'daily',
        "daysOfWeek" integer[] NULL,
        "departureTime" time NOT NULL,
        "defaultVehicleId" integer NULL,
        "autoOpen" boolean NOT NULL DEFAULT true,
        "isActive" boolean NOT NULL DEFAULT true,
        "horizonDays" integer NOT NULL DEFAULT 14,
        "createdByUserId" integer NOT NULL,
        "createdAt" timestamp NOT NULL DEFAULT now(),
        "updatedAt" timestamp NOT NULL DEFAULT now(),
        CONSTRAINT "CHK_transport_route_schedule_type" CHECK ("scheduleType" IN ('daily','selected_days')),
        CONSTRAINT "CHK_transport_route_schedule_horizon" CHECK ("horizonDays" BETWEEN 1 AND 31),
        CONSTRAINT "FK_transport_route_schedule_provider" FOREIGN KEY ("providerId") REFERENCES public.transport_provider(id) ON DELETE CASCADE,
        CONSTRAINT "FK_transport_route_schedule_route" FOREIGN KEY ("routeId") REFERENCES public.transport_route(id) ON DELETE CASCADE,
        CONSTRAINT "FK_transport_route_schedule_vehicle" FOREIGN KEY ("defaultVehicleId") REFERENCES public.vehicle(id) ON DELETE SET NULL
      )
    `);
    await q.query(`CREATE INDEX IF NOT EXISTS "IDX_transport_route_schedule_provider_route" ON public.transport_route_schedule ("providerId","routeId","isActive")`);
    await q.query(`ALTER TABLE public.transport_run ADD COLUMN IF NOT EXISTS "scheduleId" integer NULL`);
    await q.query(`ALTER TABLE public.transport_run ADD COLUMN IF NOT EXISTS "autoGenerated" boolean NOT NULL DEFAULT false`);
    await q.query(`CREATE UNIQUE INDEX IF NOT EXISTS "UQ_transport_run_schedule_departure" ON public.transport_run ("scheduleId","scheduledDeparture") WHERE "scheduleId" IS NOT NULL`);
  }

  public async down(q: QueryRunner): Promise<void> {
    await q.query(`DROP INDEX IF EXISTS public."UQ_transport_run_schedule_departure"`);
    await q.query(`ALTER TABLE public.transport_run DROP COLUMN IF EXISTS "autoGenerated"`);
    await q.query(`ALTER TABLE public.transport_run DROP COLUMN IF EXISTS "scheduleId"`);
    await q.query(`DROP TABLE IF EXISTS public.transport_route_schedule`);
  }
}
