/**
 * seed-routes.ts — One-time seed for the intercity_route table
 *
 * Run with:
 *   npx ts-node -r tsconfig-paths/register src/database/seed-routes.ts
 *
 * Or call seedRoutes() from AppModule onApplicationBootstrap() for auto-seeding.
 *
 * Data based on real Tanzania bus/transport routes:
 * - Fees are conservative starting points — admin can adjust via RouteManagement
 * - estimatedDays are working days (exclude weekends for bus routes)
 * - Routes are bidirectional — each direction is a separate row
 */

export const TANZANIA_ROUTE_SEEDS = [
  // ── DAR ES SALAAM HUB — most frequent routes ──────────────────────────────
  {
    originCity: 'Dar es Salaam',
    destinationCity: 'Mwanza',
    estimatedDays: 2,
    baseShippingFee: 8000,
    perKgFee: 1500,
    primaryTransport: 'bus',
    notes:
      'Via Morogoro–Dodoma corridor. Kilimanjaro/Scandinavian buses daily.',
  },
  {
    originCity: 'Mwanza',
    destinationCity: 'Dar es Salaam',
    estimatedDays: 2,
    baseShippingFee: 8000,
    perKgFee: 1500,
    primaryTransport: 'bus',
  },
  {
    originCity: 'Dar es Salaam',
    destinationCity: 'Arusha',
    estimatedDays: 1,
    baseShippingFee: 6000,
    perKgFee: 1200,
    primaryTransport: 'bus',
    notes: 'Direct buses. ~8hrs. Arusha Bus Terminal.',
  },
  {
    originCity: 'Arusha',
    destinationCity: 'Dar es Salaam',
    estimatedDays: 1,
    baseShippingFee: 6000,
    perKgFee: 1200,
    primaryTransport: 'bus',
  },
  {
    originCity: 'Dar es Salaam',
    destinationCity: 'Moshi',
    estimatedDays: 1,
    baseShippingFee: 6500,
    perKgFee: 1200,
    primaryTransport: 'bus',
    notes: 'Via Arusha. ~9hrs.',
  },
  {
    originCity: 'Moshi',
    destinationCity: 'Dar es Salaam',
    estimatedDays: 1,
    baseShippingFee: 6500,
    perKgFee: 1200,
    primaryTransport: 'bus',
  },
  {
    originCity: 'Dar es Salaam',
    destinationCity: 'Dodoma',
    estimatedDays: 1,
    baseShippingFee: 5000,
    perKgFee: 1000,
    primaryTransport: 'bus',
    notes: 'Direct ~5hrs. Capital City Express buses.',
  },
  {
    originCity: 'Dodoma',
    destinationCity: 'Dar es Salaam',
    estimatedDays: 1,
    baseShippingFee: 5000,
    perKgFee: 1000,
    primaryTransport: 'bus',
  },
  {
    originCity: 'Dar es Salaam',
    destinationCity: 'Mbeya',
    estimatedDays: 2,
    baseShippingFee: 9000,
    perKgFee: 1800,
    primaryTransport: 'bus',
    notes: 'TAZARA corridor. ~12hrs. Moderners/Fresh Ya Bus.',
  },
  {
    originCity: 'Mbeya',
    destinationCity: 'Dar es Salaam',
    estimatedDays: 2,
    baseShippingFee: 9000,
    perKgFee: 1800,
    primaryTransport: 'bus',
  },
  {
    originCity: 'Dar es Salaam',
    destinationCity: 'Tanga',
    estimatedDays: 1,
    baseShippingFee: 4500,
    perKgFee: 1000,
    primaryTransport: 'bus',
    notes: 'Direct ~5hrs. Coastal road.',
  },
  {
    originCity: 'Tanga',
    destinationCity: 'Dar es Salaam',
    estimatedDays: 1,
    baseShippingFee: 4500,
    perKgFee: 1000,
    primaryTransport: 'bus',
  },
  {
    originCity: 'Dar es Salaam',
    destinationCity: 'Morogoro',
    estimatedDays: 1,
    baseShippingFee: 3500,
    perKgFee: 800,
    primaryTransport: 'bus',
    notes: '~3hrs. Very frequent buses.',
  },
  {
    originCity: 'Morogoro',
    destinationCity: 'Dar es Salaam',
    estimatedDays: 1,
    baseShippingFee: 3500,
    perKgFee: 800,
    primaryTransport: 'bus',
  },
  {
    originCity: 'Dar es Salaam',
    destinationCity: 'Iringa',
    estimatedDays: 1,
    baseShippingFee: 7000,
    perKgFee: 1400,
    primaryTransport: 'bus',
    notes: '~8hrs via Morogoro.',
  },
  {
    originCity: 'Iringa',
    destinationCity: 'Dar es Salaam',
    estimatedDays: 1,
    baseShippingFee: 7000,
    perKgFee: 1400,
    primaryTransport: 'bus',
  },
  {
    originCity: 'Dar es Salaam',
    destinationCity: 'Songea',
    estimatedDays: 3,
    baseShippingFee: 12000,
    perKgFee: 2500,
    primaryTransport: 'bus',
    notes: 'Remote route. ~18hrs via Iringa.',
  },
  {
    originCity: 'Songea',
    destinationCity: 'Dar es Salaam',
    estimatedDays: 3,
    baseShippingFee: 12000,
    perKgFee: 2500,
    primaryTransport: 'bus',
  },
  {
    originCity: 'Dar es Salaam',
    destinationCity: 'Kigoma',
    estimatedDays: 3,
    baseShippingFee: 13000,
    perKgFee: 2500,
    primaryTransport: 'bus',
    notes: 'Long route. ~22hrs via Tabora.',
  },
  {
    originCity: 'Kigoma',
    destinationCity: 'Dar es Salaam',
    estimatedDays: 3,
    baseShippingFee: 13000,
    perKgFee: 2500,
    primaryTransport: 'bus',
  },
  {
    originCity: 'Dar es Salaam',
    destinationCity: 'Tabora',
    estimatedDays: 2,
    baseShippingFee: 10000,
    perKgFee: 2000,
    primaryTransport: 'bus',
  },
  {
    originCity: 'Tabora',
    destinationCity: 'Dar es Salaam',
    estimatedDays: 2,
    baseShippingFee: 10000,
    perKgFee: 2000,
    primaryTransport: 'bus',
  },
  {
    originCity: 'Dar es Salaam',
    destinationCity: 'Zanzibar',
    estimatedDays: 1,
    baseShippingFee: 7000,
    perKgFee: 1500,
    primaryTransport: 'courier',
    notes: 'Via ferry. DHL/EMS recommended. Customs may apply.',
  },
  {
    originCity: 'Zanzibar',
    destinationCity: 'Dar es Salaam',
    estimatedDays: 1,
    baseShippingFee: 7000,
    perKgFee: 1500,
    primaryTransport: 'courier',
  },
  {
    originCity: 'Dar es Salaam',
    destinationCity: 'Lindi',
    estimatedDays: 2,
    baseShippingFee: 10000,
    perKgFee: 2000,
    primaryTransport: 'bus',
    notes: 'Via Mtwara corridor. ~14hrs.',
  },
  {
    originCity: 'Lindi',
    destinationCity: 'Dar es Salaam',
    estimatedDays: 2,
    baseShippingFee: 10000,
    perKgFee: 2000,
    primaryTransport: 'bus',
  },
  {
    originCity: 'Dar es Salaam',
    destinationCity: 'Mtwara',
    estimatedDays: 2,
    baseShippingFee: 10000,
    perKgFee: 2000,
    primaryTransport: 'bus',
    notes: '~13hrs south coast route.',
  },
  {
    originCity: 'Mtwara',
    destinationCity: 'Dar es Salaam',
    estimatedDays: 2,
    baseShippingFee: 10000,
    perKgFee: 2000,
    primaryTransport: 'bus',
  },
  {
    originCity: 'Dar es Salaam',
    destinationCity: 'Shinyanga',
    estimatedDays: 2,
    baseShippingFee: 9000,
    perKgFee: 1800,
    primaryTransport: 'bus',
  },
  {
    originCity: 'Shinyanga',
    destinationCity: 'Dar es Salaam',
    estimatedDays: 2,
    baseShippingFee: 9000,
    perKgFee: 1800,
    primaryTransport: 'bus',
  },
  {
    originCity: 'Dar es Salaam',
    destinationCity: 'Musoma',
    estimatedDays: 3,
    baseShippingFee: 11000,
    perKgFee: 2200,
    primaryTransport: 'bus',
    notes: 'Via Mwanza or direct via Singida.',
  },
  {
    originCity: 'Musoma',
    destinationCity: 'Dar es Salaam',
    estimatedDays: 3,
    baseShippingFee: 11000,
    perKgFee: 2200,
    primaryTransport: 'bus',
  },
  {
    originCity: 'Dar es Salaam',
    destinationCity: 'Bukoba',
    estimatedDays: 3,
    baseShippingFee: 12000,
    perKgFee: 2500,
    primaryTransport: 'bus',
    notes: 'Via Mwanza or ferry from Mwanza.',
  },
  {
    originCity: 'Bukoba',
    destinationCity: 'Dar es Salaam',
    estimatedDays: 3,
    baseShippingFee: 12000,
    perKgFee: 2500,
    primaryTransport: 'bus',
  },
  {
    originCity: 'Dar es Salaam',
    destinationCity: 'Singida',
    estimatedDays: 2,
    baseShippingFee: 9000,
    perKgFee: 1800,
    primaryTransport: 'bus',
  },
  {
    originCity: 'Singida',
    destinationCity: 'Dar es Salaam',
    estimatedDays: 2,
    baseShippingFee: 9000,
    perKgFee: 1800,
    primaryTransport: 'bus',
  },
  {
    originCity: 'Dar es Salaam',
    destinationCity: 'Njombe',
    estimatedDays: 2,
    baseShippingFee: 10000,
    perKgFee: 2000,
    primaryTransport: 'bus',
    notes: 'Via Iringa. ~14hrs.',
  },
  {
    originCity: 'Njombe',
    destinationCity: 'Dar es Salaam',
    estimatedDays: 2,
    baseShippingFee: 10000,
    perKgFee: 2000,
    primaryTransport: 'bus',
  },
  {
    originCity: 'Dar es Salaam',
    destinationCity: 'Kibaha',
    estimatedDays: 1,
    baseShippingFee: 2500,
    perKgFee: 500,
    primaryTransport: 'bus',
    notes: 'Very close — ~45min. Possibly same day.',
  },
  {
    originCity: 'Kibaha',
    destinationCity: 'Dar es Salaam',
    estimatedDays: 1,
    baseShippingFee: 2500,
    perKgFee: 500,
    primaryTransport: 'bus',
  },

  // ── MWANZA REGIONAL HUB ───────────────────────────────────────────────────
  {
    originCity: 'Mwanza',
    destinationCity: 'Arusha',
    estimatedDays: 2,
    baseShippingFee: 9000,
    perKgFee: 1800,
    primaryTransport: 'bus',
    notes: 'Via Shinyanga–Singida corridor.',
  },
  {
    originCity: 'Arusha',
    destinationCity: 'Mwanza',
    estimatedDays: 2,
    baseShippingFee: 9000,
    perKgFee: 1800,
    primaryTransport: 'bus',
  },
  {
    originCity: 'Mwanza',
    destinationCity: 'Musoma',
    estimatedDays: 1,
    baseShippingFee: 5000,
    perKgFee: 1000,
    primaryTransport: 'bus',
    notes: 'Lake Victoria northern route. ~3hrs.',
  },
  {
    originCity: 'Musoma',
    destinationCity: 'Mwanza',
    estimatedDays: 1,
    baseShippingFee: 5000,
    perKgFee: 1000,
    primaryTransport: 'bus',
  },
  {
    originCity: 'Mwanza',
    destinationCity: 'Bukoba',
    estimatedDays: 2,
    baseShippingFee: 8000,
    perKgFee: 1500,
    primaryTransport: 'bus',
    notes: 'Via ferry or road. Lake route option.',
  },
  {
    originCity: 'Bukoba',
    destinationCity: 'Mwanza',
    estimatedDays: 2,
    baseShippingFee: 8000,
    perKgFee: 1500,
    primaryTransport: 'bus',
  },
  {
    originCity: 'Mwanza',
    destinationCity: 'Shinyanga',
    estimatedDays: 1,
    baseShippingFee: 4500,
    perKgFee: 900,
    primaryTransport: 'bus',
    notes: '~3hrs.',
  },
  {
    originCity: 'Shinyanga',
    destinationCity: 'Mwanza',
    estimatedDays: 1,
    baseShippingFee: 4500,
    perKgFee: 900,
    primaryTransport: 'bus',
  },
  {
    originCity: 'Mwanza',
    destinationCity: 'Tabora',
    estimatedDays: 2,
    baseShippingFee: 8000,
    perKgFee: 1500,
    primaryTransport: 'bus',
  },
  {
    originCity: 'Tabora',
    destinationCity: 'Mwanza',
    estimatedDays: 2,
    baseShippingFee: 8000,
    perKgFee: 1500,
    primaryTransport: 'bus',
  },
  {
    originCity: 'Mwanza',
    destinationCity: 'Kigoma',
    estimatedDays: 2,
    baseShippingFee: 9000,
    perKgFee: 1800,
    primaryTransport: 'bus',
    notes: 'Via Tabora.',
  },
  {
    originCity: 'Kigoma',
    destinationCity: 'Mwanza',
    estimatedDays: 2,
    baseShippingFee: 9000,
    perKgFee: 1800,
    primaryTransport: 'bus',
  },

  // ── ARUSHA REGIONAL HUB ───────────────────────────────────────────────────
  {
    originCity: 'Arusha',
    destinationCity: 'Moshi',
    estimatedDays: 1,
    baseShippingFee: 3000,
    perKgFee: 600,
    primaryTransport: 'bus',
    notes: '~1hr. Very frequent.',
  },
  {
    originCity: 'Moshi',
    destinationCity: 'Arusha',
    estimatedDays: 1,
    baseShippingFee: 3000,
    perKgFee: 600,
    primaryTransport: 'bus',
  },
  {
    originCity: 'Arusha',
    destinationCity: 'Tanga',
    estimatedDays: 1,
    baseShippingFee: 5000,
    perKgFee: 1000,
    primaryTransport: 'bus',
    notes: '~5hrs coastal route.',
  },
  {
    originCity: 'Tanga',
    destinationCity: 'Arusha',
    estimatedDays: 1,
    baseShippingFee: 5000,
    perKgFee: 1000,
    primaryTransport: 'bus',
  },
  {
    originCity: 'Arusha',
    destinationCity: 'Dodoma',
    estimatedDays: 1,
    baseShippingFee: 6000,
    perKgFee: 1200,
    primaryTransport: 'bus',
  },
  {
    originCity: 'Dodoma',
    destinationCity: 'Arusha',
    estimatedDays: 1,
    baseShippingFee: 6000,
    perKgFee: 1200,
    primaryTransport: 'bus',
  },

  // ── MBEYA SOUTHERN HUB ────────────────────────────────────────────────────
  {
    originCity: 'Mbeya',
    destinationCity: 'Iringa',
    estimatedDays: 1,
    baseShippingFee: 5000,
    perKgFee: 1000,
    primaryTransport: 'bus',
    notes: '~4hrs TAZARA corridor.',
  },
  {
    originCity: 'Iringa',
    destinationCity: 'Mbeya',
    estimatedDays: 1,
    baseShippingFee: 5000,
    perKgFee: 1000,
    primaryTransport: 'bus',
  },
  {
    originCity: 'Mbeya',
    destinationCity: 'Njombe',
    estimatedDays: 1,
    baseShippingFee: 4500,
    perKgFee: 900,
    primaryTransport: 'bus',
    notes: '~3hrs mountain route.',
  },
  {
    originCity: 'Njombe',
    destinationCity: 'Mbeya',
    estimatedDays: 1,
    baseShippingFee: 4500,
    perKgFee: 900,
    primaryTransport: 'bus',
  },
  {
    originCity: 'Mbeya',
    destinationCity: 'Songea',
    estimatedDays: 2,
    baseShippingFee: 8000,
    perKgFee: 1500,
    primaryTransport: 'bus',
  },
  {
    originCity: 'Songea',
    destinationCity: 'Mbeya',
    estimatedDays: 2,
    baseShippingFee: 8000,
    perKgFee: 1500,
    primaryTransport: 'bus',
  },
  {
    originCity: 'Mbeya',
    destinationCity: 'Dodoma',
    estimatedDays: 2,
    baseShippingFee: 8000,
    perKgFee: 1500,
    primaryTransport: 'bus',
    notes: 'Via Iringa. ~10hrs.',
  },
  {
    originCity: 'Dodoma',
    destinationCity: 'Mbeya',
    estimatedDays: 2,
    baseShippingFee: 8000,
    perKgFee: 1500,
    primaryTransport: 'bus',
  },

  // ── DODOMA CENTRAL HUB ────────────────────────────────────────────────────
  {
    originCity: 'Dodoma',
    destinationCity: 'Singida',
    estimatedDays: 1,
    baseShippingFee: 4000,
    perKgFee: 800,
    primaryTransport: 'bus',
    notes: '~3hrs.',
  },
  {
    originCity: 'Singida',
    destinationCity: 'Dodoma',
    estimatedDays: 1,
    baseShippingFee: 4000,
    perKgFee: 800,
    primaryTransport: 'bus',
  },
  {
    originCity: 'Dodoma',
    destinationCity: 'Tabora',
    estimatedDays: 2,
    baseShippingFee: 8000,
    perKgFee: 1500,
    primaryTransport: 'bus',
  },
  {
    originCity: 'Tabora',
    destinationCity: 'Dodoma',
    estimatedDays: 2,
    baseShippingFee: 8000,
    perKgFee: 1500,
    primaryTransport: 'bus',
  },
  {
    originCity: 'Dodoma',
    destinationCity: 'Morogoro',
    estimatedDays: 1,
    baseShippingFee: 4500,
    perKgFee: 900,
    primaryTransport: 'bus',
    notes: '~4hrs.',
  },
  {
    originCity: 'Morogoro',
    destinationCity: 'Dodoma',
    estimatedDays: 1,
    baseShippingFee: 4500,
    perKgFee: 900,
    primaryTransport: 'bus',
  },
  // ── TRANSIT ROUTES — multi-hop, no direct bus ─────────────────────────────
  // These routes require a stopover at a transit city.
  // The system shows buyers the full path and total days.
  // Super Agent at transit city receives and re-dispatches next day.

  // Mbinga — no direct bus from Dar, must go via Songea
  {
    originCity: 'Dar es Salaam',
    destinationCity: 'Mbinga',
    estimatedDays: 2,
    baseShippingFee: 14000,
    perKgFee: 2800,
    primaryTransport: 'bus',
    transitCity: 'Songea',
    leg1Days: 1,
    leg2Days: 1,
    notes: 'Via Songea — basi la Dar→Songea kila siku, Songea→Mbinga asubuhi',
  },
  {
    originCity: 'Mbinga',
    destinationCity: 'Dar es Salaam',
    estimatedDays: 2,
    baseShippingFee: 14000,
    perKgFee: 2800,
    primaryTransport: 'bus',
    transitCity: 'Songea',
    leg1Days: 1,
    leg2Days: 1,
  },
  {
    originCity: 'Songea',
    destinationCity: 'Mbinga',
    estimatedDays: 1,
    baseShippingFee: 5000,
    perKgFee: 1000,
    primaryTransport: 'bus',
    notes: 'Moja kwa moja — ~3hrs',
  },
  {
    originCity: 'Mbinga',
    destinationCity: 'Songea',
    estimatedDays: 1,
    baseShippingFee: 5000,
    perKgFee: 1000,
    primaryTransport: 'bus',
  },

  // Kasulu — via Kigoma
  {
    originCity: 'Dar es Salaam',
    destinationCity: 'Kasulu',
    estimatedDays: 3,
    baseShippingFee: 15000,
    perKgFee: 3000,
    primaryTransport: 'bus',
    transitCity: 'Kigoma',
    leg1Days: 2,
    leg2Days: 1,
    notes: 'Via Kigoma',
  },
  {
    originCity: 'Kasulu',
    destinationCity: 'Dar es Salaam',
    estimatedDays: 3,
    baseShippingFee: 15000,
    perKgFee: 3000,
    primaryTransport: 'bus',
    transitCity: 'Kigoma',
    leg1Days: 1,
    leg2Days: 2,
  },
  {
    originCity: 'Kigoma',
    destinationCity: 'Kasulu',
    estimatedDays: 1,
    baseShippingFee: 4000,
    perKgFee: 800,
    primaryTransport: 'bus',
    notes: '~2hrs',
  },
  {
    originCity: 'Kasulu',
    destinationCity: 'Kigoma',
    estimatedDays: 1,
    baseShippingFee: 4000,
    perKgFee: 800,
    primaryTransport: 'bus',
  },

  // Mpanda — via Tabora
  {
    originCity: 'Dar es Salaam',
    destinationCity: 'Mpanda',
    estimatedDays: 3,
    baseShippingFee: 15000,
    perKgFee: 3000,
    primaryTransport: 'bus',
    transitCity: 'Tabora',
    leg1Days: 2,
    leg2Days: 1,
    notes: 'Via Tabora',
  },
  {
    originCity: 'Mpanda',
    destinationCity: 'Dar es Salaam',
    estimatedDays: 3,
    baseShippingFee: 15000,
    perKgFee: 3000,
    primaryTransport: 'bus',
    transitCity: 'Tabora',
    leg1Days: 1,
    leg2Days: 2,
  },
  {
    originCity: 'Tabora',
    destinationCity: 'Mpanda',
    estimatedDays: 1,
    baseShippingFee: 6000,
    perKgFee: 1200,
    primaryTransport: 'bus',
  },
  {
    originCity: 'Mpanda',
    destinationCity: 'Tabora',
    estimatedDays: 1,
    baseShippingFee: 6000,
    perKgFee: 1200,
    primaryTransport: 'bus',
  },

  // Masasi — via Mtwara
  {
    originCity: 'Dar es Salaam',
    destinationCity: 'Masasi',
    estimatedDays: 3,
    baseShippingFee: 13000,
    perKgFee: 2500,
    primaryTransport: 'bus',
    transitCity: 'Mtwara',
    leg1Days: 2,
    leg2Days: 1,
    notes: 'Via Mtwara',
  },
  {
    originCity: 'Masasi',
    destinationCity: 'Dar es Salaam',
    estimatedDays: 3,
    baseShippingFee: 13000,
    perKgFee: 2500,
    primaryTransport: 'bus',
    transitCity: 'Mtwara',
    leg1Days: 1,
    leg2Days: 2,
  },
  {
    originCity: 'Mtwara',
    destinationCity: 'Masasi',
    estimatedDays: 1,
    baseShippingFee: 4500,
    perKgFee: 900,
    primaryTransport: 'bus',
  },
  {
    originCity: 'Masasi',
    destinationCity: 'Mtwara',
    estimatedDays: 1,
    baseShippingFee: 4500,
    perKgFee: 900,
    primaryTransport: 'bus',
  },

  // Geita — via Mwanza
  {
    originCity: 'Dar es Salaam',
    destinationCity: 'Geita',
    estimatedDays: 3,
    baseShippingFee: 11000,
    perKgFee: 2200,
    primaryTransport: 'bus',
    transitCity: 'Mwanza',
    leg1Days: 2,
    leg2Days: 1,
    notes: 'Via Mwanza',
  },
  {
    originCity: 'Geita',
    destinationCity: 'Dar es Salaam',
    estimatedDays: 3,
    baseShippingFee: 11000,
    perKgFee: 2200,
    primaryTransport: 'bus',
    transitCity: 'Mwanza',
    leg1Days: 1,
    leg2Days: 2,
  },
  {
    originCity: 'Mwanza',
    destinationCity: 'Geita',
    estimatedDays: 1,
    baseShippingFee: 4000,
    perKgFee: 800,
    primaryTransport: 'bus',
    notes: '~2hrs',
  },
  {
    originCity: 'Geita',
    destinationCity: 'Mwanza',
    estimatedDays: 1,
    baseShippingFee: 4000,
    perKgFee: 800,
    primaryTransport: 'bus',
  },

  // Bariadi — via Shinyanga
  {
    originCity: 'Dar es Salaam',
    destinationCity: 'Bariadi',
    estimatedDays: 3,
    baseShippingFee: 12000,
    perKgFee: 2500,
    primaryTransport: 'bus',
    transitCity: 'Shinyanga',
    leg1Days: 2,
    leg2Days: 1,
  },
  {
    originCity: 'Bariadi',
    destinationCity: 'Dar es Salaam',
    estimatedDays: 3,
    baseShippingFee: 12000,
    perKgFee: 2500,
    primaryTransport: 'bus',
    transitCity: 'Shinyanga',
    leg1Days: 1,
    leg2Days: 2,
  },
  {
    originCity: 'Shinyanga',
    destinationCity: 'Bariadi',
    estimatedDays: 1,
    baseShippingFee: 4000,
    perKgFee: 800,
    primaryTransport: 'bus',
  },
  {
    originCity: 'Bariadi',
    destinationCity: 'Shinyanga',
    estimatedDays: 1,
    baseShippingFee: 4000,
    perKgFee: 800,
    primaryTransport: 'bus',
  },

  // Babati — via Arusha
  {
    originCity: 'Dar es Salaam',
    destinationCity: 'Babati',
    estimatedDays: 2,
    baseShippingFee: 10000,
    perKgFee: 2000,
    primaryTransport: 'bus',
    transitCity: 'Arusha',
    leg1Days: 1,
    leg2Days: 1,
    notes: 'Via Arusha',
  },
  {
    originCity: 'Babati',
    destinationCity: 'Dar es Salaam',
    estimatedDays: 2,
    baseShippingFee: 10000,
    perKgFee: 2000,
    primaryTransport: 'bus',
    transitCity: 'Arusha',
    leg1Days: 1,
    leg2Days: 1,
  },
  {
    originCity: 'Arusha',
    destinationCity: 'Babati',
    estimatedDays: 1,
    baseShippingFee: 5000,
    perKgFee: 1000,
    primaryTransport: 'bus',
  },
  {
    originCity: 'Babati',
    destinationCity: 'Arusha',
    estimatedDays: 1,
    baseShippingFee: 5000,
    perKgFee: 1000,
    primaryTransport: 'bus',
  },

  // Mwanza → Mbinga (very long, via Dar)
  {
    originCity: 'Mwanza',
    destinationCity: 'Mbinga',
    estimatedDays: 4,
    baseShippingFee: 20000,
    perKgFee: 4000,
    primaryTransport: 'bus',
    transitCity: 'Dar es Salaam',
    leg1Days: 2,
    leg2Days: 2,
    notes: 'Via Dar — Mwanza→Dar 2 siku, Dar→Mbinga 2 siku',
  },
  {
    originCity: 'Mbinga',
    destinationCity: 'Mwanza',
    estimatedDays: 4,
    baseShippingFee: 20000,
    perKgFee: 4000,
    primaryTransport: 'bus',
    transitCity: 'Dar es Salaam',
    leg1Days: 2,
    leg2Days: 2,
  },
  // Songwe / Tunduma — near Mbeya, Zambia border town
  {
    originCity: 'Dar es Salaam',
    destinationCity: 'Songwe',
    estimatedDays: 2,
    baseShippingFee: 10000,
    perKgFee: 2000,
    primaryTransport: 'bus',
    transitCity: 'Mbeya',
    leg1Days: 2,
    leg2Days: 1,
    notes: 'Via Mbeya — karibu na mpakani wa Zambia',
  },
  {
    originCity: 'Songwe',
    destinationCity: 'Dar es Salaam',
    estimatedDays: 2,
    baseShippingFee: 10000,
    perKgFee: 2000,
    primaryTransport: 'bus',
    transitCity: 'Mbeya',
    leg1Days: 1,
    leg2Days: 2,
  },
  {
    originCity: 'Dar es Salaam',
    destinationCity: 'Tunduma',
    estimatedDays: 2,
    baseShippingFee: 10000,
    perKgFee: 2000,
    primaryTransport: 'bus',
    transitCity: 'Mbeya',
    leg1Days: 2,
    leg2Days: 1,
    notes: 'Via Mbeya — Tunduma ni karibu na Songwe, mpaka wa Zambia',
  },
  {
    originCity: 'Tunduma',
    destinationCity: 'Dar es Salaam',
    estimatedDays: 2,
    baseShippingFee: 10000,
    perKgFee: 2000,
    primaryTransport: 'bus',
    transitCity: 'Mbeya',
    leg1Days: 1,
    leg2Days: 2,
  },
  {
    originCity: 'Mbeya',
    destinationCity: 'Songwe',
    estimatedDays: 1,
    baseShippingFee: 3000,
    perKgFee: 600,
    primaryTransport: 'bus',
    notes: '~1hr moja kwa moja',
  },
  {
    originCity: 'Songwe',
    destinationCity: 'Mbeya',
    estimatedDays: 1,
    baseShippingFee: 3000,
    perKgFee: 600,
    primaryTransport: 'bus',
  },
  {
    originCity: 'Mbeya',
    destinationCity: 'Tunduma',
    estimatedDays: 1,
    baseShippingFee: 3000,
    perKgFee: 600,
    primaryTransport: 'bus',
    notes: '~1hr moja kwa moja',
  },
  {
    originCity: 'Tunduma',
    destinationCity: 'Mbeya',
    estimatedDays: 1,
    baseShippingFee: 3000,
    perKgFee: 600,
    primaryTransport: 'bus',
  },
];

/**
 * Use this in your super-agents.service.ts or a dedicated seed controller:
 *
 *   async seedRoutes() {
 *     for (const route of TANZANIA_ROUTE_SEEDS) {
 *       await this.upsertRoute({ ...route, isActive: true });
 *     }
 *     return { seeded: TANZANIA_ROUTE_SEEDS.length };
 *   }
 *
 * Or add a temporary admin endpoint:
 *   GET /super-agents/admin/seed-routes  (remove after first run)
 */
